### ISSUE TITLE
[US] As an attestation consumer, I want to be able to check if an address has an attestation using the ERC-1155 owner method

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#109]
As an attestation consumer,
I want to be able to check if an address has an attestation using the ERC-1155 owner method,
So that I can consume attestations without having to write new code for my dapps

----

### Description

Further to implementing the erc-721 standard for reading state on the portal level, we should also implement the erc-1155 standard by overloading the `balanceOf` function with the following implementation (in the `AttestationRegistry` contract:

```Solidity
    /**
        @notice Get the balance of an account's tokens.
        @param _owner  The address of the token holder
        @param _id     ID of the token
        @return        The _owner's balance of the token type requested
     */
    function balanceOf(address _owner, uint256 _id) external view returns (uint256);
```

We can also add the erc-1155 `balanceOfBatch` function.

```Solidity
    /**
        @notice Get the balance of multiple account/token pairs
        @param _owners The addresses of the token holders
        @param _ids    ID of the tokens
        @return        The _owner's balance of the token types requested (i.e. balance for each (owner, id) pair)
     */
    function balanceOfBatch(address[] calldata _owners, uint256[] calldata _ids) external view returns (uint256[] memory);
```

The erc-1155 token standard is also seeing widespread adoption, and is implemented widely, especially in the gaming sector.  This standard aligns more with the attestation registry, as the addition of the `_id` parameter allows us to specify an attestation id (when cast from `uint256` to `bytes32`) which effectively allows a dapp to query if a user has been given an attestation on a specific schema.

**Comment by satyajeetkolhapure** [comment]
Hi @orbmis @alainncls,

One doubt on statement -` id parameter allows us to specify a schema id (when cast from bytes32 to uint256)`

Currently we store schema id as `keccak256(abi.encodePacked(schemaString))`, how does unit256 relate to it?

**Comment by alainncls** [comment]
Following a regression introduced after merging this ticket's PR, we're reopening the ticket.
