### ISSUE TITLE
[US] As an Issuer, I want to set the `attester` address via my Portal

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#154]
Currently the `attester` field of the attestation metadata is set to `tx.origin` in `AttestationRegistry.sol`:

https://github.com/Consensys/linea-attestation-registry/blob/77a4e2be81abd600b173cce7b848b04bbc73313b/src/AttestationRegistry.sol#L103

This is going to cause issues when an issuer's workflow involves letting user's "claim" attestations directly from the portal, because it means that the user's wallet's address will be the value of the `attester` field, which has two implications:

1. semantically it doesn't make sense, because it implies the user has issued an attestation to themselves
2. it may have implications for users that are using ERC-4337 smart contract wallets, as `tx-origin` will be the bundler
3. it means that only that user can revoke their own credential, because the `tx.origin` value is compared to the `attester` field during the revocation process, meaning an issuer may not be able revoke attestations they've issued. See the following line of code for reference:

https://github.com/Consensys/linea-attestation-registry/blob/77a4e2be81abd600b173cce7b848b04bbc73313b/src/AttestationRegistry.sol#L136

----

Solution, allow the portal to set the value of the `attester` field, by allowing them to pass this value as a parameter to the `attest` function.

**Comment by alainncls** [comment]
In order to make possible the issuance of attestations where the attester is the end-user, let's create an example Portal "AutoIssuerPortal".

**Comment by alainncls** [comment]
To help create Portals more easily, from our partners feedback:

- In Portal: `attest`, `bulkAttest`, `revoke` and `bulkRevoke` should be public, to be called by a child contract
- In Portal: `supportsInterface` should be virtual to be overridden to cover other interfaces
- More documentation on AbstractPortal to make Portal creation easier
