### ISSUE TITLE
[US] As a user, I want to test an attestation using an on-chain portal

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#168]
As a user,
I want to test an attestation using an on-chain portal,
So that I can be confident my transaction will result in the attestation that I intended

----

This involves the same workflow and logic involved in creating an attestation, but the last step involves returning the attestation to the user instead of putting it in the registry.  This can be used for testing purposes, so that a dapp / user can verify an attestation will be created properly by a portal when given a specific set of inputs.

This can be a new method that is added to the `AbstractPortal` and/or the `DefaultPortal` contracts.  With some refactoring, it could potentially re-use the same internal logic for verifying an inbound attestation request and creating an `Attestation` from an `AttestationPayload`.

Can also be used for off-chain attestation verification if that's a requirement.

**Comment by alainncls** [comment]
Might probably be sufficiently covered by Wagmi's transaction simulation

**Comment by axelcazorla** [comment]
bravo !1!
