### ISSUE TITLE
[US] As a user, I want to retrieve an attestation from the registry

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#171]
As a user,
I want to retrieve an attestation from the registry,
So that I can see an attestation directly from source

----

## Description

This will require a few steps:

1. Retrieve the attestation using the `getAttestation(bytes32 attestationId)` method from the `AttestationRegistry`
2. Get the respective schema from the `SchemaRegistry` using the `getSchema(bytes32 schemaId)` with the schema id from the attestation metadata
3. Parse the schema string and use this to `abi.decode` the attestation data
4. Create an object from the values in the decoded data and the field names in the schema string
5. Optionally retrieve the portal information from the portal registry as qualifying information for the attestation

**NOTE:** initially we may be able to leverage a lot of this from the indexer and / or subgraph, which could do a lot of the parsing for us.  Whether this is feasible is TBD.

**Comment by fksyuan** [comment]
The PR have submitted. The link is: https://github.com/Consensys/linea-attestation-registry/pull/339
