### ISSUE TITLE
[US] As I user, I want to query all attestations that has a specific value for a specific schema field

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#172]
As I user,
I want to query all attestations that has a specific value for a specific schema field,
So that I can run advanced queries that are relevant to me use case

----

## Description

This feature has a hard dependency on the subgraph / indexer, but will be a very useful feature for many dapps.  This requires searching for all attestations with a specific schema id, and where the attestation data includes a specific subset of bytes.

Once we primary results are are retrieved, the attestations are then decoded according to the schema, and filtered so that the series of bytes in the attestation are verified to match the specific value in the schema that has been specific in the search criteria.

This last part can either be done client side, if using a subgraph, or can be done by the indexer.

**Comment by alainncls** [comment]
Done in #268
