### ISSUE TITLE
Topic 2 - Schema specification

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#2]
A Schema is a standardized and reusable template that defines the structure of Attestation data. It is designed to be independent of any specific business validation rules, as validation business rules will be handled by Modules. Instead, Schema’s main purpose is to provide a clear description of the expected data that should be filled in by the Attestation Issuer.

In addition to describing the expected data, a Schema also specifies how this data should be serialized and deserialized from the blockchain storage. This ensures that the data can be easily exchanged and interpreted by different components or systems that interact with the Attestation.

A Schema consists of a set of fields, each associated with a specific Data Type. These fields define the attributes or properties that an Attestation can have. For example, a Schema may include fields such as "timestamp" to indicate when the Attestation was issued, "issuer" to identify the entity issuing the Attestation, "subject" to specify the entity being attested, and "data" to hold the actual content or information being attested. Each field is assigned a Data Type, which can be a basic type like string, integer, or boolean, or it can be a custom-defined type specific to the application's needs.

The business intent behind the Linear Attestation Service is to maximize the composability and reusability of existing Schemas and Modules. This means that Schemas are designed to be versatile and compatible with different Attestors. Multiple Attestors can use the same Schema to ensure consistency and interoperability. Additionally, the service encourages the creation of new Schemas by allowing anyone to define and contribute their own Schemas.

To facilitate the discovery and adoption of Schemas, it is important to establish a mechanism for making Schemas easily accessible. This enables users to explore and select from a range of existing Schemas rather than creating new ones from scratch. By promoting the reuse of Schemas, the Linear Attestation Service aims to streamline the development and deployment of Attestation systems while maintaining consistency and compatibility across different entities and applications.

The creator of a Schema should be able to add some context about their Schema. A dedicated field will be available for the creator to put a text or a URL.

Here is the list of technical challenges and technical decisions to be collectively discussed and accepted:

1. One or Many schemas per Attestor
2. Schema with collections of fields or objects
3. Schema with nested objects
4. Self reflecting and cross-reflecting Schemas
5. Linking Attestations
6. Data Types
7. Enforcement of standards
9. Nullable (required or not) fields => not covered in this Topic. Pushed to the [Topic #12](../issues/12)

## 1. One or Many schemas per Attestor
At first glance, only one Schema should be set for an Attestor. Nevertheless, two benefits can be imagined by having multiple schemas for an Attestor:

### a. Attestor as a First Class Citizen with reputation

We could consider Attestors as First Class Citizens. This means that they could have different unrelated business domains Schemas, using the same list of Modules as attached to the Attestor.

As an Attestor would become more widely used over time, as it can serve different business domains, it has the potential to gain popularity and trust within the community. The increased usage contributes to building its reputation.

Eg: One Attestor, having a Module “Eth Payment”, using DID schema or Quest Schema
* One Attestation Issuer wants to use a well known and trusted Attestor to attest users identity, with ETH payment to create the attestation (DID)
* Another one wants also a well known and trusted Attestator, with ETH payment, but to attest a task completion (Quest)

The Attestor configuration would be as follows:
<p align="center">
<img width="429" alt="image" src="https://github.com/Consensys/linea-attestation-registry/assets/5026039/2919ea58-0d11-43eb-a3d5-f9ab79301eb5">
</p>
Different Attestation Issuer would use the Attestor as follows:
<p align="center">
<img width="599" alt="image" src="https://github.com/Consensys/linea-attestation-registry/assets/5026039/0a805aff-024f-41b5-b07e-9a5ceefe0852">
</p>

**Pro’s and Con’s**
Pro's:
* Ensure Attestator reliability and trust;
* Creates a much more comprehensive list of Attestors and direct usability, from Attestation Issuer point of view;
* Concentrate Attestations registration around Blue Chip Attestators;

Con's:
* From Attestion Issuer perspective, it adds complexity, as he has to understand and know that there are several Schemas available, and know which one he has to use;
* Hard to cover all use cases, and eventually, new Attestators should be created (need other schema, need other module); Otherwise, we should consider the possibility to attach new Schemas or Modules to an existing Attestor, that opens new rules to design: who can add a Schema, who can add a Module, how to replace one, ...
* From technical perspective, it would add complexity to the following technical topics, not yet fully designed at this stage:
  * How to ensure that all Modules are compatible with each Schema: For instance, if a Module needs to verify a specific field value, should all the Schemas attached to the Attestor using this Module include that field?
  * Dealing with Modules expected data is not trivial and not yet designed. We are still exploring how Modules will be able to access and interpret data from the Attestation Data (as discussed in [Topic #9](../issues/9)). For instance, if a Module needs to verify a zero-knowledge proof (zkp), it remains unclear whether this zkp should be described in the Schema or not. Considering the complexity of this topic, the presence of multiple Schemas for an Attestor would introduce additional layers of complexity.
  * The current on-chain discoverability mechanism is highly inefficient (will be eventually covered by an off-chain indexer - not in the current scope of work), and introducing a link from an Attestation to a Schema would further decrease efficiency and complicate the implementation of looping. For instance, if an Attestor is restricted to having only one unique Schema, retrieving and listing all its Attestations is already a hard process for a user. User would need to obtain the count of Attestations and retrieve them individually using index-based access. If we were to introduce the concept of linking an Attestation to one of the available Schemas for the Attestor, it would add even more complexity in the discoverability process.
 
 
### b. Complex Attestations with different objects to attest

Objects that are connected and associated with the same Business Domain should be attested through the same Attestor, leading to have a unified set of Schemas under an Attestor.
Two approached can be imagined to create Attestations with this coherent set of Schemas:

Eg: an Attestation Issuer wants to attest that students are registered for courses
<p align="center">
<img width="320" alt="image" src="https://github.com/Consensys/linea-attestation-registry/assets/5026039/504a566b-2ab1-4480-af85-cce8bb1dc609">
</p>
Two approaches could be imagined to add Attestations within this coherent set of Schemas:

* Approach 1: “Per entity approach”
* Approach 2: “Aggregate Root approach” (assuming Student is the AR in the following example)
<p align="center">
<img width="610" alt="image" src="https://github.com/Consensys/linea-attestation-registry/assets/5026039/95a3c33d-7785-44dc-9c37-cb1f5d4de31c">
</p>

**Pro’s and Con’s**
Pro's:
* Creates de-facto a super reliable data schema;

Con's:
* From Attestion Issuer perspective, it adds complexity, as he has to understand (depending on the approach) how to create a new Attestation
* As the prefered approach would be "Per entity" approach, having multiple Schemas for Attestor becomes useless, as it could be done by linking Attestions from different Attestors (see technical design below)

----

**DECISION TO BE TAKEN ("Decision 1"): Is it required for an Attestor to have exactly one Schema, or can it have multiple Schemas?**

----
## 2. Schema with collections of field values

EAS describes Schema with a simple list of types and field name.
As an example, the following functional description of a Schema would lead to the following calldata:

Functional description of the Schema "Person":
```javascript
schema Person {
    string   firstName;
    string   lastName;
    uint256  dobTimeStamp;
}
```

Corresponding calldata:
`string firstName, string lastName, uint256 dobTimeStamp`
<p align="center">
<img width="387" alt="image" src="https://github.com/Consensys/linea-attestation-registry/assets/5026039/96833258-8599-43e9-92c5-9025bc5b41de">
</p>
The built-in types available are discussed further in this topic: see: 8. Data Types

This representation works perfectly for flat array Schemas. But how to handle collections.
As an example, here is the functional description of a Schema with a collection of timestamps:
```javascript
schema Person {
    string     		firstName;
    string     		lastName;
    uint256[]  		eventsTimeStamps;
}
```
Lists can be added in flat arrays, just by using the convention `[]`

Notes:
* Parsing Schema calldata is a technical challenge to be discussed in [Topic #12](../issues/12)
* As EAS does, SchemaId should be the keccack of the schema description / calldata. It prevents de-facto the creation of two identical Schemas and it is easy to compute

----

**DECISION TO BE TAKEN ("Decision 2a"): Shall we use EAS convention to code flat array Schemas?**
**DECISION TO BE TAKEN ("Decision 2b"): Shall we use the convention [] to code collections?**

----

## 3. Schema with nested objects

Schema should be able to handle nested objects

Say we have the following functional description of Schemas:
Functional description of the Schema "Patent":
```javascript
schema Patent {
    string   name;
    string   number;
    Person  creator;
}
```
Functional description of the Schema "Person":
```javascript
schema Person {
    string   firstName;
    string   lastName;
}
```

Three different approaches can be elaborated to handle this situation
### a. Keep using EAS style
Extending the EAS convention, we could define a the Patent Schema as follows:

`string name, string number, {string firstName, string lastName} creator`

**Pro’s and Con’s**
Pro's:
* No need to create nested Schema, as the whole structure in described in a single transaction

Con's:
* Becomes pretty unreadable
* Does not foster the creation of re-usable schemas

### b. Link a Schema from a Schema
We can imagine that 
* First, the Attestor Configurator creates the Schema Person; eventually, this Schema will be used for the Schema Patent, but also for anyone else willing to use a Schema Person; Assuming that the SchemaId of the Person is `894a...2147f`(keccack("string firstName,string lastName"))
* In a second time, the Attestor Configurator creates the Schema Patent. In this Schema, the type to code the Person, would be the schemaId of the Schema Person, leading to the following schema description / calldata: 
`string name, string number, 894a...2147f creator`

By extrapolation, collection of objects can be defined using the convention `[]`; eg with a Schema Patent having several creators: `string name, string number, 894a...2147f[] creators`

**Pro’s and Con’s**
Pro's:
* Foster the creation / re-utilisation of existing Schemas

Con's:
* Need to create nested Schema
* There is a technical challenge not solved: how to parse a Schema, to be discussed in [Topic #12](../issues/12)

### c. Use json-schema or other highly descriptive standard
Con's: That would not be feasible on-chain

----

**DECISION TO BE TAKEN ("Decision 3"): Shall we use define nested objects, by linked a Schema field to another Schema?**

----

### a. Self reflecting Schemas
A Schema should be able to have itself as a linked Schema.
Functional description of the Schema "Person" where the key `father` points out to a Person:
```javascript
schema Person {
    string    firstName;
    string    lastName;
    Person  father;
}
```

In this situation, it is not possible to know the SchemaId of the Schema Person, as there is a circular reference for the relation Person.

To designate the circularly referenced Schema, the most effective approach would be to utilize the reserved type 'Self' to cover this situation. Hence, the description / calldata of this Schema would be: `string firstName,string lastName,self father`

### b. Cross reflecting Schemas
Two Schemas could be cross-reflecting.
Functional description of the Schema "Person" and a Schema "Residence", where both Schemas have at least one property that references the other Schema.

```javascript
schema Person {
    string             firstName;
    string             lastName;
    Residence     residence;
}
```
```javascript
schema Residence {
    string             description;
    string             zipCode;
    Person           owner;
}
```

Given this cross-reflection, it is not possible to create these Schemas, as we do not know the SchemaId of the Schema Person before creating the Schema Residence, that needs the SchemaId Person to be created.
Many workarounds exist, like creating higher objects, or having a different business data model.

Workaround with higher objects:
```javascript
schema Person {
    string                          firstName;
    string                          lastName;
    OwnedResidence      residence;
}
```
```javascript
schema OwnedResidence {
    Person            owner;
    Residence      residence;
}
```
```javascript
schema Residence {
    string             description;
    string             zipCode;
}
```

----

**DECISION TO BE TAKEN ("Decision 4a"): Self-reflecting type is coded with the type `self`**
**DECISION TO BE TAKEN ("Decision 4b"): It is not possible to create cross-reflecting Schemas**

----

## 5. Linking Attestations
Schema construction taken apart, Attestations should be linkable to other Attestation.

__For the sake of clarity, linking Attestation is not related to referring a Schema as a property of a Schema (elaborated in the precedent chapter).__

Two questions appears when it comes to link Attestations:
- Should the link between Attestations be enforced in the Schema or not?
- How could it be implemented?

Here is a functional description of an Attestation "Patent" where the creator is one Attestation "Person":

```javascript
patentPhone = Patent {"Phone", Attestation Person("personAlexanderBell")}
```
```javascript
personAlexanderBell = Person {"Alexander", "Bell"}
```

### a. Linking Attestations enforced on the Schema or not
At first glance, we can imagine that the Schema is responsible to enforce the fact that a nested object of the Schema is hydrated by an existing Attestation and that data expected from the Attestation Issuer is the AttestationId.
On the other hand, we could assume that the Schema does not tell anything about links between Attestations, and this responsibility is pushed backed to a Module.

**Pro’s and Con’s having the Schema responsible to enforce linking**
Pro's:
* If not handled through the Schema description, it would be complex to code this behaviour in a Module
* Allows to have consistent data content for a Schema . If this is not enforced at the Schema level, some Attestations may have specific content, manually pushed by sometimes and pointing out an Attestation some other times.
Con's:
* Brings business logic within the Schema, which is considered as a non business artefact

### b. How could it be implemented?
Considering that Schema is responsible to enforce the link between Attestations, how could it be implemented in the description / calldata of a Schema?

**First approach**: designate the AttestorId, wearing the expected Schema:
Say we have an Attestor whose Schema is "Person". Its id is `Attestor1234`
Hence, when creating the Schema "Patent", we would have the following description / calldata of the Schema:
```string name,  Attestor1234 creator```

**Second approach**: designate the SchemaId:
Say we have a Schema "Person", with Id `Schema9876`
Hence, when creating the Schema "Patent", we would have the following description / calldata of the Schema:
```string name,  Schema9876 creator```

**Pro’s and Con’s having the First approach**
Pro's:
* Allow to enforce the business rules that have been invoked by the Modules of the Attestor, instead of having any Attestor using the Schema Person, without any corresponding and expected business rules. As an example, assuming that the Person Schema is used by two Attestors. One is a "famous" one, with "serious" modules that does interesting and expected checks. The other Attestor using the Schema Person is a dummy Attestor, created by someone, without any module or signature verification. If we link the the Patent Schema to only a SchemaId, the Attestation Issuer will have to pick an AttestationId among all the Attestators having this Schema. The Attestation Issuer will not know what are the relevant Attestors to use for his purpose.
* If we were to use a SchemaId as the key to describe the link between Attestations, we would have a conflict with what has been defined to describe the nesting of objects in a Schema, as both would use the Id of the Schema to specify it

Con's:
* Brings business logic within the Schema, which is considered as a non business artefact

---

**DECISION TO BE TAKEN ("Decision 5a"): Should the link between Attestations be enforced in the Schema or not?**
**DECISION TO BE TAKEN ("Decision 5b"): Should link description be done with AttestorId or SchemaId?**

----
## 6. Data Types
We can imagine two different approaches to define the Data Types available when creating a Schema.
* Approach 1: a defined list of human-readable types for the average guy (string, number, boolean, date, datetime, URL, …)
* Approach 2: all the solidity primitive types (see [EAS](https://easscan.org/schema/create))

---

**DECISION TO BE TAKEN ("Decision 6"): Should Data Types be solidity primitives or human-readable types?**

----

## 7. Enforcement of standards

Bringing standards could be a huge benefit for schema interoperability (eg: force using Schema.org conventions). Nevertheless, at this stage, it is hard to imagine a coercive mean to force user to use a standard

---

**DECISION TO BE TAKEN ("Decision 7"): No enforcement of the standard is expected?**

----

**Comment by astralblue** [comment]
I agree with most of @orbmis's assessments, except I'm not sure if we can actually enforce links on an ongoing basis.  The challenge comes from (the proposed addition of) revocations: If an attestation A (issued by X) refers to another attestation B (issued by Y), then later B is revoked, there are a few enforcement actions, similar to SQL's referential integrity enforcement via `ON DELETE` clause:

* `SET NULL`/`SET DEFAULT` – alter A's referencing field.  Not possible because an attestation and all its fields are immutable once published.
* `CASCADE` – revoke A as well.  Not possible if X != Y.  It may also have a gas implication if the fan-out is huge.
* `NO ACTION`/`RESTRICT` – prevent the revocation.  This is probably the only technically feasible option at the moment.

However, even `NO ACTION`/`RESTRICT` have a real-life implication, and it opens up the need for semantic clarification of "revocation":

* If Y wanted to retract B because it used to reflect their opinion but does not anymore, Y should be able to do so.
* However, if A referred to B in order to, for example, express X's approval/disapproval of Y's opinion as of its initial publication, it should be also possible to keep A, as Y's change of heart does not invalidate A's past opinions.

IMO this can be solved if we agreed that an attestation captures an instantaneous, immutable snapshot of something that may still evolve over time, and an attestation cannot really be retracted (in the sense that it's to be deemed invalid/nonexistent) once published, but can only be fully superseded/partially updated by publishing another attestation that links to the original attestation.
