### ISSUE TITLE
[US] Attestation Read Interoperability

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#231]
As an attestation consumer,
I want to be able to read from multiple registries from a single location,
So that I don't have to check which registry an attestation id refers to

----

Description

This feature involves creating a smart contract that accept an attestation id, and read from a number of registries

To begin with, we will default to interoperability with EAS, with a view to adding more registries later when needed.

This contract will expose a function called: `getAttestation(bytes32 uid)`, which by default will return an EAS standard attestation.

This function will call the `getAttestation` function on the EAS registry, which can be found here:

https://github.com/ethereum-attestation-service/eas-contracts/blob/04a5846723bfc7fc7e9dc75582958aca66a1ba4a/contracts/EAS.sol#L378C25-L378C25

If no attestation is found (unsure how to determine this exactly), then the code will check the Verax registry by calling the function:  `getAttestation(bytes32 attestationId)` on the `AttestationRegistry` contract, which cane found here:

https://github.com/Consensys/linea-attestation-registry/blob/0362d40e124a751ae600241afc3967fefd586065/src/AttestationRegistry.sol#L236C12-L236C49

If the attestation is found in the Verax registry, then we will need to transform it from a Verax to EAS attestation, like so:

```Solidity
struct Attestation {
    bytes32 uid; // taken from "attestationId"
    bytes32 schema; // taken from "schemaId"
    uint64 time; // taken from "attestedDate"
    uint64 expirationTime; // taken from "expirationDate"
    uint64 revocationTime; // taken from "revocationDate"
    bytes32 refUID; // default to bytes32(0)
    address recipient; // taken from "subject". (will need to be converted from bytes to address)
    address attester; // taken from "attester"
    bool revocable; // will need to be looked up at the portal level
    bytes data; // taken from "attestationData"
}
```

----

As well as exposing a method for retrieving an attestation, we will also expose a method for retrieving a schema string, which will look like this:

```Solidity
  function getSchema(bytes32 schemaId) public view returns (string);
```

This will first call the `getSchema` function on the EAS `SchemaRegistry`, and if found, will return the `schema` property of the return schema.  If not found, then it will call the `getSchema` function on the Verax `SchemaRegistry` and return the `schema` property of the returned schema.

**Comment by 0xEillo** [comment]
What is the reasoning for having this as a smart contract as oppose to just the SDK?
