### ISSUE TITLE
[US] As a Verax dev, I want the core smart contracts to be TransparentUpgradable

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#28]
As a Verax developper,
I want the all core contract to be upgradeable.
So that I can later add new features 

## Requirements
* Use transparent proxy pattern

## Todo
- [ ] As there are no common practices to implement TransparentUpgradeable with Foundry, see how some scripts have been created to perform that
- [ ] Implement it for the already existing core contracts (among `SchemaRegistry`, `ModuleRegistry`, `PortalRegistry` and `AttestationRegistry`

## Acceptance criteria
* The SchemaRegistry deployment script has been updated
* Unit-test to validate the upgrade can be done successfully 

### Additional information

| Workload estimate |
|--------|
| TBD |

**Comment by arthur-remy** [comment]
@alainncls I guess we will need to add [gaps](https://ethereum.stackexchange.com/questions/148544/how-many-storage-gaps-to-add-at-the-end-of-base-upgradeable-contracts) as well.
(Mentioning it because it's something we forgot to do at the beginning on other projects
