### ISSUE TITLE
[US] As a user, I want to know how many attestations were issued by a given Portal

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#294]
As a user,
I want to know how many attestations were issued by a given Portal,
So that I can easily get this relevant information and make it available for an explorer

----

NOTE: Ping us on Discord to be allowlisted on our Graph Nodes

1. On the subgraph, change the `Portal` entity to include an `attestationCounter` field
2. On the subgraph, change the `handleAttestationRegistered` handler to increment the `attestationCounter` field of the matching `Portal`

**Comment by satyajeetkolhapure** [comment]
![Image](https://github.com/Consensys/linea-attestation-registry/assets/77279246/d50fb2ce-cf69-4218-9e48-b37fdd9720be)
