### ISSUE TITLE
[BUG] As an issuer, I can update another issuer's schema context

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#301]
**Steps to reproduce:**

Allowlist an issuer address
Using the allowlisted wallet, register a schema
Allowlist another different issuer address
Using the new allowlisted wallet, update the schema context for the previously created schema

**Expected Outcome:**

The second issuer should not be able to update the context of the schema created by the first issuer

**Actual Outcome:**

The second issuer IS able to update the context of the schema created by the first issuer

**Comment by zhanymkanov** [comment]
Sounds interesting. Issuers operate with schemas only by it's `schemaId` so I guess just saving the creator of the schema would be ok?

**Comment by zhanymkanov** [comment]
I think it would be ok to forbid to update old schema for all and kindly ask issuers to redeploy their schemas.
