### ISSUE TITLE
[BUG] The NFTPortal cannot be registered

### ISSUE THREAD

**Issue by dingning-aspecta** [Consensys/linea-attestation-registry#310]
**Describe the bug** A clear and concise description of what the bug is.
The NFTPortal cannot be registered

**To Reproduce** Steps to reproduce the behavior:

1. Deploy the NFTPortal
2. Register the NFTPortal just deployed through PortalRegistry
3. Registration failed. See error

**Expected behavior** A clear and concise description of what you expected to happen.
The NFTPortal should declare that the IPortal interface is implemented

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://github.com/Consensys/linea-attestation-registry/assets/107902133/6bbc2f7f-0e97-4583-b9a1-200feb470838)

**Additional context** Add any other context about the problem here, e.g. transaction hash, network name etc.
![image](https://github.com/Consensys/linea-attestation-registry/assets/107902133/bd90b71d-15ca-4afb-bee6-ac0c31f10a74)
The new version of PortalRegistry checks whether portal implements the IPortal interface. Because NFTPortal overrides supportsInterface, it needs to explicitly declare that it implements the IPortal interface.

**Comment by dingning-aspecta** [comment]
@alainncls Hi, if possible, I would like to contribute code to this issue. Thank you.

**Comment by alainncls** [comment]
@dingning-aspecta of course, that would be great! Go for it!
We probably have the same issue with the other Portal examples, no?

**Comment by dingning-aspecta** [comment]
> @dingning-aspecta of course, that would be great! Go for it! We probably have the same issue with the other Portal examples, no?

Thank you. 

It seems that other Portals do not have this issue because other Portals do not override `supportsInterface` function. But I will confirm it later.
