### ISSUE TITLE
[TASK] Optimize the gas cost of "for loops"

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#349]
Following @Aryan9592 PR #101 , optimise the "for loops" in the contracts without loosing the readability of the code.

**Comment by Aryan9592** [comment]
Just got this issue as a notification...Noticed three of your contracts i.e `AttestationRegistry.sol, ModuleRegistry.sol and SchemaRegistry.sol` can be optimized in this way if you exclude the contracts within libraries, interfaces, types, and examples.

**Comment by Aryan9592** [comment]
I see, Just import that `uncheckedInc256` from `Common.sol` and replace `i++` with `i = uncheckedInc256(i)` 

Is there a need to change `uint256 i = 0;` to `uint256 i;`. I feel that might affect the readability
