### ISSUE TITLE
[BUG] Relationship schema IDs are different on testnet and mainnet

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#556]
The canonical relationship schema is different on testnet and mainnet because the schema string has brackets in one instance, and none on the other.  The docs need to be updated on the documentation site and in the readme file

**Comment by alainncls** [comment]
Documentation updated: https://docs.ver.ax/verax-documentation/developer-guides/for-attestation-issuers/link-attestations
Readme file updated via PR #560
