### ISSUE TITLE
[US] As a User, I want to see a disclaimer on the expiration date

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#570]
As a User,  
I want to see a disclaimer on the expiration date,  
So that I better understand this data.

----

Attestations can expire, and the Issuer determines the duration of their validity.  
Consumers of these Attestations can choose whether to follow this expiration date or not.

Therefore, we need to add a tooltip to the Expiration Date on the [Attestation Detail page](https://explorer.ver.ax/linea/attestations/0x0000000000000000000000000000000000000000000000000000000000592d71).  

We need to add an '[information icon](https://fontawesome.com/icons/circle-info?f=classic&s=regular)' on the same line as the Expiration Date, and display a tooltip on hover with the following message: "The validity of this Attestation is determined by the Issuer, and consumers may choose to adhere to or ignore this expiration date."

**Comment by Chirag-S-Kotian** [comment]
this one for me
