### ISSUE TITLE
2deuces9ers

### ISSUE THREAD

**Issue by Deuces9ers** [Consensys/linea-attestation-registry#632]
Yes we can!

_Originally posted by @alainncls in https://github.com/Consensys/linea-attestation-registry/pull/22#discussion_r1277687204_

**Comment by alainncls** [comment]
How can we help you @Deuces9ers ?

**Comment by Deuces9ers** [comment]
i truly need all the help i can get. I havent found any funds yet to pay for services i obviously need.

**Comment by alainncls** [comment]
?
