### ISSUE TITLE
[SPIKE] As a Verax Dev, I know how Attestee (or Subject) is handled

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#64]
As a Verax Dev,
I want to be able to implement the notion of Attestee (or Subject)

## Requirements
 * Conceptualise what is an Attestee (or Subject)
 * Create the tickets for implementation in MVP 1

## Acceptance criteria
I have all the tickets to implement the Attestee (or Subject) in MVPV1

### Additional information

| Workload estimate | Dependency |
|--------|--------|
| TBD | TBD |

**Comment by orbmis** [comment]
Can you provide more information on what is need in this ticket @fdemiramon ?
