### ISSUE TITLE
Topic 7 - Portal Specifications

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#7]
The Portal is a smart contract. Most of the use cases would be using the defaultPortal, deployable through a unique transaction.

The Portal is the gateway between the end-user (the attestation issuer) and the Attestation registry.
It is responsible for:
1/ To expose a method to end-users to Create Attestation(s). No specifciations are to be defined here. It is the role of the Portal to expose the ABI in regards to what it is supposed to do. bulk attest, EIP 612 sig check, .... The Portal has full power to twist, amend, modify data provided by the end-user, before sending them to modules.
2/ If it wants, the Portal can call the modules. From convention point of view, it is highly recommended that it uses the Modules of Verax. But no enforcement is set to prevent that. If the Portal wants to do bulk creation, create complex links within the payload of the end-user or whatever, it can do it by calling multiple times a set of Modules. It can also call some modules on some conditions or not. It can also calculate a score per Module that the payload validates or not
3/ Create the attestation on the AttestationRegistry: Doing whatever it wants, the Portal has the right (because it is registered) to create an Attestation. The only inputs expected by the AttestationRegistry are schemaId and attestationData. If for example, the Portal is responsible for bulk attestation, it will call x times the AttestationRegistry to create all the attestations

Now, if I am an average guy, willing to create a new Portal without dev skills, the PortalRegistry will expose the following method to deploy a defaultPortal with the cloneProxy of OZ:
deployAndRegisterDefaultPortal(bytes32 schemaId, address[] modules)
This defaultPortal will:
expose a method attest(attestationPayload, validationPayload)
calls the modules
create the attestation

**Comment by astralblue** [comment]
I reviewed the draft above and am fine with it, no objections <3
