### ISSUE TITLE
[BUG] Explorer - The search is case sensitive

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#721]
## Steps to reproduces

1. Search for `0x4793304e1da8e7cee8ad4163b5fdc8a87e4e3c7F` on https://explorer.ver.ax/linea/search?search_query=0x4793304e1da8e7cee8ad4163b5fdc8a87e4e3c7F
2. Search for `0x4793304e1da8e7cee8ad4163b5fdc8a87e4e3c7f` on https://explorer.ver.ax/linea/search?search_query=0x4793304e1da8e7cee8ad4163b5fdc8a87e4e3c7f

## Expected behaviour

These 2 searches should yield the same result as they are the same string, except for the capitalization.

## Current behaviour

The first search doesn't give any result, while the second one gives a result.

**Comment by fdemiramon** [comment]
hello @alainncls !
