### ISSUE TITLE
[US] As a user, I want to see Expired and Revoked Attestations with a watermark on the Subject page

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#755]
As a user,
I want to see Expired and Revoked Attestations with a watermark on the Subject page,
So that it's easier to identify the most relevant Attestations

----

> [!NOTE]
> Depends on
> - #703 

While displaying the Cards for Attestations on the Subject Page:
- If the Attestation is flagged as revoked, the card display should be greyed and a red 'Revoked' watermark applied to it
- If the Attestation is expired (expiration date < current date), the card display should be greyed and a 'Expired' watermark applied to it => Add a tooltip to say that some consumers might still consider it as valid

**Comment by arthur-remy** [comment]
Proposed "wireframe" as discussed

![Image](https://github.com/user-attachments/assets/2161089d-8b42-4ee2-876f-35b43ad5d895)

**Comment by arthur-remy** [comment]
Last designed for expired card
![Image](https://github.com/user-attachments/assets/5d1b35be-6c2a-401c-98a9-547e0135d340)
