### ISSUE TITLE
[US] As a user, I want to see indication that I am currently looking at a filtered view of Attestations

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#762]
As a user,
I want to see indication that I am currently looking at a filtered view of Attestations,
So that this view is easier to understand

----

## Problem

The current "Filtered Views," accessed from the Issuer page when users want to see all the Attestations from an Issuer or for a specific Attestation Type, do not indicate which category the displayed Attestations belong to.

Instead, the same heading/button from the page showing all Attestations is being displayed.

This leads to confusion for users regarding the content of the page.

## Solution to implement

Replace the generic "Explore Attestations" title with specific text for each filter.

### When filtering by Attestation Type

- The title should be `[Issuer name] - [Attestation Type]`.
- The page is accessed when clicking on a specific Attestation Type for an Issuer. Example [here](https://explorer.ver.ax/linea/attestations?where=%7B%22portal_%22%3A%7B%22id%22%3A%220xbdec68492d69a7ff1fb4c2abf5c28ade535dc88a%22%7D%2C%22schema_%22%3A%7B%22id%22%3A%220x6350a66dfb1aebcab88bb92c6fc179eb618472b7e0a95dee7ca5982a34610030%22%7D%7D).
- Technical solution: when filtering by `portal + schema`, fetch the corresponding Attestation Type name from the [data file](https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/pages/Home/data.tsx).
- Fallback case: if the `portal + schema` filter doesn't yield any match in the dataset, the default title should be `Attestations matching Portal "[Portal name]" for Schema "[Schema name]"`.

### When filtering by Issuer

- The title should be `Attestations from [Issuer name]`.
- The page is accessed when clicking on the number of Attestations for an Issuer. Example [here](https://explorer.ver.ax/linea/attestations?where=%7B%22portal_in%22%3A%5B%220x187410ed494f9444f71769267be79b544933e36f%22%2C%220x64fed12012847003a8dc5105f4e5d1a1314b8fc4%22%2C%220x78edd28beec8d9f53612516e0beefc1b9bf95d7f%22%2C%220xbdec68492d69a7ff1fb4c2abf5c28ade535dc88a%22%5D%7D).
- Technical solution: when filtering by `portal_in`, fetch the corresponding Issuer name from the [data file](https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/pages/Home/data.tsx).
- Fallback case: if the `portal_in` filter doesn't yield any match in the dataset, the default title should be `Attestations from [Portal owner name]` (considering the first Portal in the array). In this case, a call to get the Portal is necessary to retrieve the owner’s name.

> [!WARNING]
> The customized title should be consistently displayed regardless of whether the user is navigating internally within the Explorer or accessing the page via an external link.

**Comment by alainncls** [comment]
> For Issuer attestations: "Attestations from [Issuer name]"

Right now we don't have such a page, should we push that to an other ticket?

**Comment by arthur-remy** [comment]
I was thinking of the page which is accessed through the button on the screenshot. So for instance at [this URL](https://explorer.ver.ax/linea/attestations?where=%7B%22portal_in%22%3A%5B%220x187410ed494f9444f71769267be79b544933e36f%22%2C%220x64fed12012847003a8dc5105f4e5d1a1314b8fc4%22%2C%220x78edd28beec8d9f53612516e0beefc1b9bf95d7f%22%2C%220xbdec68492d69a7ff1fb4c2abf5c28ade535dc88a%22%5D%7D)

![Image](https://github.com/user-attachments/assets/36532099-5df1-435b-a42f-a58db2d37323)

**Comment by alainncls** [comment]
@arthur-remy very true! Thanks for reminding me! I'm amending the description then!

**Comment by Stasn13** [comment]
working on it, could you please assign it to me?
