### ISSUE TITLE
[TASK] Make the "error handler" give more information

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#769]
Currently, the [`errorHandler`](https://github.com/Consensys/linea-attestation-registry/blob/f340f7c10bc6d4173e0c907eadcc21ce5b879091/sdk/src/utils/errorHandler.ts#L4) can only throw contextualized errors when their signature matches with the ABIs contained in the SDK.

1. In the case where the error is of type `ContractFunctionRevertedError`, but doesn't have an "errorName", use its signature.
2. In the case where the error is not of type `ContractFunctionRevertedError`, use its "shortMessage".
3. In the fallback case, change the generic message to `${type} failed`.

**Comment by Chirag-S-Kotian** [comment]
please assign this task to me

**Comment by Chirag-S-Kotian** [comment]
hey @alainncls how to run the development server in pnpm here ,i already installed pnpm i

**Comment by alainncls** [comment]
Hey @Chirag-S-Kotian 👋 

So, you should start by installing all the dependencies: `pnpm i`
Then you can develop on the [errorHandler](https://github.com/Consensys/linea-attestation-registry/blob/dev/sdk/src/utils/errorHandler.ts) file and add more unit test in the [corresponding test file](https://github.com/Consensys/linea-attestation-registry/blob/dev/sdk/src/utils/errorHandler.test.ts).

Once your implementation gives you satisfaction and you have a good set of tests to cover it, you can then open a PR on this repo, from your forked repo. You can check [GitHub's documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) to do so 😃

**Comment by alainncls** [comment]
Ah yes, I see. When you installed the dependencies, it also installed a pre-commit hook with [husky](https://github.com/typicode/husky). It runs a few commands while committing your changes. Those commands are defined [here](https://github.com/Consensys/linea-attestation-registry/blob/dev/.husky/pre-commit).

And you can't use npm on this repo, it's based on pnpm solely.

What you need to check, is the linting and formatting of the code you've added/modified, it must follow the rules defined for the repo.

**Comment by Chirag-S-Kotian** [comment]
I already checked linting and prettier through pnpm ,there is no problem in terminal ,then it gives something git error problem 😕

**Comment by alainncls** [comment]
You can ignore the checks while committing: https://graphite.dev/guides/git-commit-skip-hooks#how-to-skip-git-commit-hooks
We'll see via the CI if there really is an issue with the code then.

**Comment by alainncls** [comment]
> here i forked this repo from dev branch https://github.com/Consensys/linea-attestation-registry.git and my repo is https://github.com/Chirag-S-Kotian/linea-attestation-registry.git it is also in dev branch i cant push the code to my forked repo could you please help me to resolve this error

Is see that you managed to open a PR #777 , that's great! 👍 
Let me check it out!
