### ISSUE TITLE
[US] As an Issuer, I want to pass my custom ABI to the SDK to get contextualized errors

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#770]
As an Issuer,
I want to pass my custom ABI to the SDK to get contextualized errors,
So that my application can handle error cases seemlessly

----

Currently, only the errors defined in the `DefaultPortal` ABI (and main registries ABI are taken into account when handling an error thrown by a transaction simulation.

This story aims to add a parameter/option to the SDK Portal's function (attest, replace, etc.) to pass a custom ABI for the Issuer's Portal. This ABI would be merged to the default one, so that all errors can be thrown in a contextual manner.

**Comment by Chirag-S-Kotian** [comment]
assign this to me and tell me where exactly this code is.

**Comment by Chirag-S-Kotian** [comment]
i need help, where exactly should i modify the code ?

**Comment by alainncls** [comment]
> i need help, where exactly should i modify the code ? i dont know which file in SDK folder @alainncls

Hey! So, the ultimate approach would be to pass the custom ABI as an option, when initializing the SDK. But that implies a strong refactoring, let's avoid it for now.

Instead, let's pass this new _optional_ parameter to the write functions of the `PortalDataMapper`:

- [ ] [`attest`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L47)
- [ ] [`attestV2`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L104)
- [ ] [`bulkAttest`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L115)
- [ ] [`revoke`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L129)
- [ ] [`bulkRevoke`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L138)
- [ ] [`replace`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L161)
- [ ] [`bulkReplace`](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L200)

All these functions would also pass this parameter to their respective 'simulateXXX` function.
And finally, this custom ABI would be concatenated with the default one [here](https://github.com/Consensys/linea-attestation-registry/blob/316d91fcec6f0f9f8a34861ba8b7d2bd2c3063ad/sdk/src/dataMapper/PortalDataMapper.ts#L304).

Ping me if that's not clear 🙂
