### ISSUE TITLE
[US] As a user, I want the registry to check the integrity of my attestation metadata

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#78]
As an attestation issuer,
I want the registry to check the integrity of my attestation metadata,
So that I can be confident that the metadata is correct

----

### Description

When calling the `attest` function, the registry should perform certain integrity checks:

- [ ] the `attestationId` does not already exist
- [x] the `attestationId` is created deterministically (e.g. auto-increment, or keccak hash)
- [x] the `schemaId` exists
- [x] the `attester` field is set to `tx.origin`
- [x] the `portalId` is set to the `msg.sender`
- [x] the `subject` field is not blank (or is of minimum length - 8 bytes?)
- [x] the `attestedDate` field is set to the current date
- [ ] the `revoked` field is uninitialized
- [x] the version is set to the current version of the registry
- [x] the `attestationData` field is not blank

### pseudocode

```Solidity
    // verify the schema id exists
    if (!schemaRegistry.isRegistered(attestation.schemaId)) revert SchemaNotRegistered();

    // the subject field is not blank (or is of minimum length - 8 bytes?)
    if (attestation.subject.length == 0) revert EmptyAttestationSubjectField();

    // the attestationData field is not blank
    if (attestation.attestationData.length == 0) revert DataAttestationFieldEmpty();
```

**Comment by satyajeetkolhapure** [comment]
@orbmis The first requirement is no longer valid as it is auto increment and there is no possibility at the moment for the duplicate
