### ISSUE TITLE
[US] As a user, I want to easily access Verax documentation and website

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#781]
As a user,
I want to easily access Verax documentation and website,
So that I can save some time

----

![Image](https://github.com/user-attachments/assets/d1cddc13-5b4d-4ca3-8d6e-bf7458c6060f)
The 2 blocks at the bottom of the Explorer's homepage should be updated.

- [ ] The left one should link to the [Developer Guide](https://docs.ver.ax/verax-documentation/developer-guides/for-attestation-issuers) on the Documentation
- [ ] The right one should link to the [main landing page](https://www.ver.ax/)

**Comment by Chirag-S-Kotian** [comment]
assign this to me.

**Comment by Chirag-S-Kotian** [comment]
i want this

**Comment by alainncls** [comment]
> i want this

Then it's yours!
