### ISSUE TITLE
[US] As a user, I want the Portal page to display links to the Portal contract and owner addresses

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#782]
As a user,
I want the Portal page to display links to the Portal contract and owner addresses,
So that I can easily access its code and details

----

Currently, the [Portal page](https://explorer.ver.ax/linea/portals/0xb86b3e16b6b960fd822849fd4b4861d73805879b) displays the Ethereum address for the Portal and the Ethereum address of its owner.
Instead of raw text, the goal of this feature is to turn them into links to chain explorers.

This can be achieved by using the `getBlockExplorerLink` function.

**Comment by Chirag-S-Kotian** [comment]
assign this to me.

**Comment by Chirag-S-Kotian** [comment]
hy @alainncls can i work on this??

**Comment by alainncls** [comment]
> hy @alainncls can i work on this??

Yes you can!

**Comment by Chirag-S-Kotian** [comment]
tell me under which folder i can find the necessary code/files.
