### ISSUE TITLE
[US] As a user, I want the Portal page to display latest Attestations

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#783]
As a user,
I want the Portal page to display latest Attestations,
So that I can get some examples of what can be achieved with this Portal

----

Currently, the [Portal page](https://explorer.ver.ax/linea/portals/0xb86b3e16b6b960fd822849fd4b4861d73805879b) displays the (optional) Modules leveraged by the Portal.

The goal of this feature is to add more interesting data by displaying the last 5 Attestations issued through this Portal.
This can be achieved exactly the same way it's already done on the [Schema page](https://explorer.ver.ax/linea/schemas/0x01f031da36192c34057c764239eb77bb6ec8ebfb808f72a7bb172f37a5bec31f).

**Comment by Chirag-S-Kotian** [comment]
assign this to me

**Comment by Chirag-S-Kotian** [comment]
where exactly i can find the code for this issue

**Comment by alainncls** [comment]
> where exactly i can find the code for this issue

Here is the [Portal page](https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/pages/Portal/index.tsx), were we'd like to add the last 5 Attestations.
That was already done on the [Schema page](https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/pages/Schema/index.tsx), so you can probably find some inspiration there.
