### ISSUE TITLE
[US] As a user, I want the Module page to display Portals leveraging it

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#784]
As a user,
I want the Module page to display Portals leveraging it,
So that I can get some examples of where it is used

----

Currently, the [Module page](https://explorer.ver.ax/linea/modules/0xe4756068c0ab70bc3c3a3b0c81be07a18bb9a502) only displays some metadata defining the Module.

The goal of this feature is to add more interesting data by displaying up to 5 Portals using this Module.
The design for this feature can be achieved exactly the same way it's already done on the [Schema page](https://explorer.ver.ax/linea/schemas/0x01f031da36192c34057c764239eb77bb6ec8ebfb808f72a7bb172f37a5bec31f).
The query should look for Portals where the `modules` array contains the current Module's address.

**Comment by Chirag-S-Kotian** [comment]
assign this to me.

**Comment by Chirag-S-Kotian** [comment]
Give me more details for this issue
