### ISSUE TITLE
[BUG] def get_starred_lists_limit():
   """
   Returns the maximum number of starred lists a user can have.
   """
   return 324 

### ISSUE THREAD

**Issue by Maniseyedi** [Consensys/linea-attestation-registry#800]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here, e.g. transaction hash, network name etc.

**Comment by alainncls** [comment]
Hey @Maniseyedi, can you explain that a bit more maybe?

**Comment by Maniseyedi** [comment]
> Hey @Maniseyedi, can you explain that a bit more maybe?

Hello, dear friend, what should I explain?

**Comment by alainncls** [comment]
> Hello, dear friend, what should I explain?

I'm not sure I understand the issue you're facing here
