### ISSUE TITLE
[TASK] Cleanup and improvements

### ISSUE THREAD

**Issue by satyajeetkolhapure** [Consensys/linea-attestation-registry#94]
- [x] Naming convention for test methods
- [ ] Naming convention for private & internal variables & functions (cf. [Solidity Style Guide](https://docs.soliditylang.org/en/latest/style-guide.html#underscore-prefix-for-non-external-functions-and-variables))
- [x] Use MIT license tag in all solidity files
- [x] Add missing deployment scripts for any contracts if any
- [x] Add NatSpec comments where they're missing
- [x] Remove all `import {Vm}` in tests (as it's already imported through `import {Test}`)
- [x] Linting warnings

**Comment by alainncls** [comment]
Naming convention for private & internal variables & functions is not followed everywhere, we should rename them to start with a _, but doing so breaks the upgradeability (storage collision).
cf. #219 
So we'll no cover this for the moment at least.
